### ISSUE TITLE
Incomplete words counted as actual words

### ISSUE THREAD

**Issue by Klamercho** [fayrose/Scrabble#1]
When placing a word, you can write only some initial parts of it *example* you can write the word REAL, you can write just REA and the algorithm will count it as valid word. 

Line: 
  if self.word not in dictionary:
                return "Please enter a valid dictionary word.\n"

**Comment by fayrose** [comment]
Fixed, thanks for pointing this out :)

Sorry for the slow response! I haven't worked on this repo in years, since before I even entered uni. Surprised it gained so much traction.
